### ISSUE TITLE
Figure out why images get messed up after using `save()`.

### ISSUE THREAD

**Issue by BautistaDalmasso** [ransomw/the-benevolent-dictators#11]
If you save and image after a xor it will get some artifacts.

Alternatively `pillow` seems to have a xor operation but I can't figure out how to get the images into the correct mode. Maybe using this xor will fix the problems? https://discord.com/channels/267624335836053506/1139999145327865879/1146963822557528134

**Comment by BautistaDalmasso** [comment]
This is more or less solved by #12 .

**Comment by ransomw** [comment]
to restate:  the issue is that (`A xor B` yields `C`) and (`B xor C` does not yield `A`) -- unless using `.bmp` images.  we're blaming this on the compression algorithm, but we're not really sure
