### ISSUE TITLE
Move the config for tesseract location somewhere else.

### ISSUE THREAD

**Issue by BautistaDalmasso** [ransomw/the-benevolent-dictators#33]
Having to make a brand new folder somewhere outside of the projects location is a bit of a handful.
Also maybe add a command to automatically make the config when passing the tesseract location.
(Leaving this here so I can remember tomorrow).

**Comment by BautistaDalmasso** [comment]
Solved in #34

**Comment by ransomw** [comment]
i think #34 created this issue anew by removing `appdirs`

**Comment by ransomw** [comment]
#36 resolves.  ty!
